/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatorio2.view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import obligatorio2.model.Estudiante;
import obligatorio2.model.Sistema;

/**
 *
 * @author diego
 */
public class AltaEquipo extends javax.swing.JFrame {
    
    private Sistema sistema;

    /**
     * Creates new form AltaEquipo
     */
    public AltaEquipo(Sistema s) {
        initComponents();
        sistema = s;
        this.cargarEstudiantes();
        lstEquipo.setModel(modeloEquipo);
        lstEquipos.setModel(modeloEquipos);
    }
    
    private void cargarEstudiantes(){
        ArrayList<Estudiante> listaEstudiantes = sistema.getListaEstudiantes();
        if (listaEstudiantes.size() > 0){
            for (int i = 0; i < listaEstudiantes.size(); i++){
                modeloEstudiante.addElement(listaEstudiantes.get(i));
            }
            lstEstudiantes.setModel(modeloEstudiante);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEstudiantes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEstudiantes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstEquipo = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnCrearEquipo = new javax.swing.JButton();
        btnEliminarEstudianteLista = new javax.swing.JButton();
        pnlEquipo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEquipos = new javax.swing.JList<>();

        jScrollPane1.setViewportView(lstEstudiantes);

        jScrollPane3.setViewportView(lstEquipo);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCrearEquipo.setText("Crear");
        btnCrearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEquipoActionPerformed(evt);
            }
        });

        btnEliminarEstudianteLista.setText("Eliminar");
        btnEliminarEstudianteLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudianteListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEstudiantesLayout = new javax.swing.GroupLayout(pnlEstudiantes);
        pnlEstudiantes.setLayout(pnlEstudiantesLayout);
        pnlEstudiantesLayout.setHorizontalGroup(
            pnlEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstudiantesLayout.createSequentialGroup()
                .addGroup(pnlEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, Short.MAX_VALUE)
                .addGroup(pnlEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEstudiantesLayout.createSequentialGroup()
                        .addComponent(btnCrearEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEstudianteLista, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlEstudiantesLayout.setVerticalGroup(
            pnlEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstudiantesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addGroup(pnlEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrearEquipo)
                        .addComponent(btnEliminarEstudianteLista)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(lstEquipos);

        javax.swing.GroupLayout pnlEquipoLayout = new javax.swing.GroupLayout(pnlEquipo);
        pnlEquipo.setLayout(pnlEquipoLayout);
        pnlEquipoLayout.setHorizontalGroup(
            pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEquipoLayout.setVerticalGroup(
            pnlEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEquipoLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Object e = lstEstudiantes.getSelectedValue();
        if(modeloEquipo.size() > 0){
            boolean objetoExistente = false;
            for (int i = 0; i < modeloEquipo.size(); i++){
                Object o = modeloEquipo.get(i);
                Estudiante eq = (Estudiante)o;
                e = (Estudiante)e;
                if(e.equals(eq)){
                    objetoExistente = true;
                }
            }
            if(!objetoExistente){
                modeloEquipo.addElement(e);
            }
        } else {
            modeloEquipo.addElement(e);
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarEstudianteListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteListaActionPerformed
        int index = lstEquipo.getSelectedIndex();
        if (index != -1) {
            modeloEquipo.remove(index);
        }    
    }//GEN-LAST:event_btnEliminarEstudianteListaActionPerformed

    private void btnCrearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEquipoActionPerformed
        if(modeloEquipo.size() == 3){
            
        } else {
            JOptionPane.showMessageDialog(this, "Los equipos deben contener 3 estudiantes", "ATENCION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearEquipoActionPerformed

    DefaultListModel modeloEstudiante = new DefaultListModel();
    DefaultListModel modeloEquipo = new DefaultListModel();
    DefaultListModel modeloEquipos = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCrearEquipo;
    private javax.swing.JButton btnEliminarEstudianteLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstEquipo;
    private javax.swing.JList<String> lstEquipos;
    private javax.swing.JList<String> lstEstudiantes;
    private javax.swing.JPanel pnlEquipo;
    private javax.swing.JPanel pnlEstudiantes;
    // End of variables declaration//GEN-END:variables
}
