/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatorio2.view;

import javax.swing.JOptionPane;
import obligatorio2.model.Sistema;



/**
 *
 * @author diego
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private Sistema sistema;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Sistema s) {
        initComponents();
        sistema = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JMenuBar();
        mnAltaEstudiante = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnDocente = new javax.swing.JMenu();
        mnAltaDocente = new javax.swing.JMenuItem();
        mnEquipo = new javax.swing.JMenu();
        mnAltaEquipo = new javax.swing.JMenuItem();
        mnProblema = new javax.swing.JMenu();
        mnAltaProblema = new javax.swing.JMenuItem();
        mnCargarSolucion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnAltaEstudiante.setText("Estudiante");

        jMenuItem1.setText("Alta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnAltaEstudiante.add(jMenuItem1);

        menuPrincipal.add(mnAltaEstudiante);

        mnDocente.setText("Docente");

        mnAltaDocente.setText("Alta");
        mnAltaDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAltaDocenteActionPerformed(evt);
            }
        });
        mnDocente.add(mnAltaDocente);

        menuPrincipal.add(mnDocente);

        mnEquipo.setText("Equipo");

        mnAltaEquipo.setText("Alta");
        mnAltaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAltaEquipoActionPerformed(evt);
            }
        });
        mnEquipo.add(mnAltaEquipo);

        menuPrincipal.add(mnEquipo);

        mnProblema.setText("Problema");

        mnAltaProblema.setText("Alta");
        mnAltaProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAltaProblemaActionPerformed(evt);
            }
        });
        mnProblema.add(mnAltaProblema);

        mnCargarSolucion.setText("Cargar Solucion");
        mnCargarSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCargarSolucionActionPerformed(evt);
            }
        });
        mnProblema.add(mnCargarSolucion);

        menuPrincipal.add(mnProblema);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AltaEstudiante altaEstudiante = new AltaEstudiante(sistema);
        altaEstudiante.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnAltaDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAltaDocenteActionPerformed
        AltaDocente altaDocente = new AltaDocente(sistema);
        altaDocente.setVisible(true);
    }//GEN-LAST:event_mnAltaDocenteActionPerformed

    private void mnAltaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAltaEquipoActionPerformed
        if (sistema.getListaEstudiantes().size() > 2){
            AltaEquipo altaEquipo = new AltaEquipo(sistema);
            altaEquipo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Deben existir al menos 3 estudiantes registrados en el sistema para registrar equipos", "ATENCION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mnAltaEquipoActionPerformed

    private void mnAltaProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAltaProblemaActionPerformed
        if(sistema.getListaDocentes().size() > 0){
            AltaProblema altaProblema = new AltaProblema(sistema);
            altaProblema.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Deben existir al menos 1 docente en el sistema para poder registrar problemas", "ATENCION", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_mnAltaProblemaActionPerformed

    private void mnCargarSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCargarSolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCargarSolucionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem mnAltaDocente;
    private javax.swing.JMenuItem mnAltaEquipo;
    private javax.swing.JMenu mnAltaEstudiante;
    private javax.swing.JMenuItem mnAltaProblema;
    private javax.swing.JMenuItem mnCargarSolucion;
    private javax.swing.JMenu mnDocente;
    private javax.swing.JMenu mnEquipo;
    private javax.swing.JMenu mnProblema;
    // End of variables declaration//GEN-END:variables
}
