/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatorio2.view;

import obligatorio2.model.Sistema;



/**
 *
 * @author diego
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private Sistema sistema;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Sistema s) {
        initComponents();
        sistema = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JMenuBar();
        mnAltaEstudiante = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnAltaDocente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnAltaEstudiante.setText("Estudiante");

        jMenuItem1.setText("Alta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnAltaEstudiante.add(jMenuItem1);

        menuPrincipal.add(mnAltaEstudiante);

        jMenu1.setText("Docente");

        mnAltaDocente.setText("Alta");
        mnAltaDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAltaDocenteActionPerformed(evt);
            }
        });
        jMenu1.add(mnAltaDocente);

        menuPrincipal.add(jMenu1);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AltaEstudiante altaEstudiante = new AltaEstudiante(sistema);
        altaEstudiante.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnAltaDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAltaDocenteActionPerformed
        AltaDocente altaDocente = new AltaDocente(sistema);
        altaDocente.setVisible(true);
    }//GEN-LAST:event_mnAltaDocenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem mnAltaDocente;
    private javax.swing.JMenu mnAltaEstudiante;
    // End of variables declaration//GEN-END:variables
}
